/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author User
 */
public class Diseño_Punto_De_Venta extends javax.swing.JFrame {

    /**
     * Creates new form Diseño_Punto_De_Venta
     */
    public Diseño_Punto_De_Venta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Foto1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabelTitulo5 = new javax.swing.JLabel();
        tlbAdd1 = new javax.swing.JButton();
        jLabelTitulo6 = new javax.swing.JLabel();
        Foto2 = new javax.swing.JButton();
        jLabelTitulo7 = new javax.swing.JLabel();
        Foto3 = new javax.swing.JButton();
        jLabelTitulo8 = new javax.swing.JLabel();
        Foto4 = new javax.swing.JButton();
        jLabelTitulo9 = new javax.swing.JLabel();
        Foto5 = new javax.swing.JButton();
        jLabelTitulo10 = new javax.swing.JLabel();
        Foto6 = new javax.swing.JButton();
        jLabelTitulo11 = new javax.swing.JLabel();
        jLabelTitulo12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPaneTablaPersona = new javax.swing.JScrollPane();
        jTablePersona = new javax.swing.JTable();
        jLabelTitulo1 = new javax.swing.JLabel();
        jLabelTitulo2 = new javax.swing.JLabel();
        jTextFieldSubTotal = new javax.swing.JTextField();
        jLabelTitulo3 = new javax.swing.JLabel();
        jTextFieldSubTotal1 = new javax.swing.JTextField();
        jLabelTitulo4 = new javax.swing.JLabel();
        jTextFieldSubTotal2 = new javax.swing.JTextField();
        jButtonIMPRIMIR = new javax.swing.JButton();
        jButtonFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(76, 179, 255));

        jLabelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("PUNTO DE VENTA");
        jLabelTitulo.setFocusCycleRoot(true);
        jLabelTitulo.setPreferredSize(new java.awt.Dimension(340, 35));
        jPanel1.add(jLabelTitulo);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        Foto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Compu3.jpeg"))); // NOI18N
        Foto1.setToolTipText("Mantenimiento de Personas");
        Foto1.setBorder(null);
        Foto1.setBorderPainted(false);
        Foto1.setFocusable(false);
        Foto1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Foto1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Foto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Foto1ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(76, 179, 255));

        jLabelTitulo5.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo5.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabelTitulo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo5.setText("Computadoras");
        jLabelTitulo5.setFocusCycleRoot(true);
        jLabelTitulo5.setPreferredSize(new java.awt.Dimension(340, 35));
        jPanel4.add(jLabelTitulo5);

        tlbAdd1.setBackground(new java.awt.Color(51, 51, 51));
        tlbAdd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ADD.png"))); // NOI18N
        tlbAdd1.setToolTipText("Mantenimiento de Personas");
        tlbAdd1.setBorder(null);
        tlbAdd1.setBorderPainted(false);
        tlbAdd1.setFocusable(false);
        tlbAdd1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tlbAdd1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabelTitulo6.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo6.setFont(new java.awt.Font("MV Boli", 0, 16)); // NOI18N
        jLabelTitulo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo6.setText("Pc gamer 2k");
        jLabelTitulo6.setFocusCycleRoot(true);
        jLabelTitulo6.setPreferredSize(new java.awt.Dimension(340, 35));

        Foto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pc_2k.png"))); // NOI18N
        Foto2.setToolTipText("Mantenimiento de Personas");
        Foto2.setBorder(null);
        Foto2.setBorderPainted(false);
        Foto2.setFocusable(false);
        Foto2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Foto2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Foto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Foto2ActionPerformed(evt);
            }
        });

        jLabelTitulo7.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo7.setFont(new java.awt.Font("MV Boli", 0, 16)); // NOI18N
        jLabelTitulo7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo7.setText("Pc gamer 4k");
        jLabelTitulo7.setFocusCycleRoot(true);
        jLabelTitulo7.setPreferredSize(new java.awt.Dimension(340, 35));

        Foto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Compu2.png"))); // NOI18N
        Foto3.setToolTipText("Mantenimiento de Personas");
        Foto3.setBorder(null);
        Foto3.setBorderPainted(false);
        Foto3.setFocusable(false);
        Foto3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Foto3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Foto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Foto3ActionPerformed(evt);
            }
        });

        jLabelTitulo8.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo8.setFont(new java.awt.Font("MV Boli", 0, 16)); // NOI18N
        jLabelTitulo8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo8.setText("Pc gamer 512GB");
        jLabelTitulo8.setFocusCycleRoot(true);
        jLabelTitulo8.setPreferredSize(new java.awt.Dimension(340, 35));

        Foto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Laptop.jpg"))); // NOI18N
        Foto4.setToolTipText("Mantenimiento de Personas");
        Foto4.setBorder(null);
        Foto4.setBorderPainted(false);
        Foto4.setFocusable(false);
        Foto4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Foto4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Foto4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Foto4ActionPerformed(evt);
            }
        });

        jLabelTitulo9.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo9.setFont(new java.awt.Font("MV Boli", 0, 16)); // NOI18N
        jLabelTitulo9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo9.setText("Laptop Asus");
        jLabelTitulo9.setFocusCycleRoot(true);
        jLabelTitulo9.setPreferredSize(new java.awt.Dimension(340, 35));

        Foto5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Laptop Asus.jpg"))); // NOI18N
        Foto5.setToolTipText("Mantenimiento de Personas");
        Foto5.setBorder(null);
        Foto5.setBorderPainted(false);
        Foto5.setFocusable(false);
        Foto5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Foto5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Foto5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Foto5ActionPerformed(evt);
            }
        });

        jLabelTitulo10.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo10.setFont(new java.awt.Font("MV Boli", 0, 16)); // NOI18N
        jLabelTitulo10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo10.setText("Laptop Asus Pro");
        jLabelTitulo10.setFocusCycleRoot(true);
        jLabelTitulo10.setPreferredSize(new java.awt.Dimension(340, 35));

        Foto6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Laptop Hp.jpeg"))); // NOI18N
        Foto6.setToolTipText("Mantenimiento de Personas");
        Foto6.setBorder(null);
        Foto6.setBorderPainted(false);
        Foto6.setFocusable(false);
        Foto6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Foto6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Foto6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Foto6ActionPerformed(evt);
            }
        });

        jLabelTitulo11.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo11.setFont(new java.awt.Font("MV Boli", 0, 16)); // NOI18N
        jLabelTitulo11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo11.setText("Laptop Gamer HP");
        jLabelTitulo11.setFocusCycleRoot(true);
        jLabelTitulo11.setPreferredSize(new java.awt.Dimension(340, 35));

        jLabelTitulo12.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo12.setFont(new java.awt.Font("MV Boli", 0, 16)); // NOI18N
        jLabelTitulo12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo12.setText("Agregar");
        jLabelTitulo12.setFocusCycleRoot(true);
        jLabelTitulo12.setPreferredSize(new java.awt.Dimension(340, 35));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(Foto1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabelTitulo6, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(Foto2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabelTitulo7, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(Foto3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabelTitulo8, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(Foto4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabelTitulo9, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(Foto5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabelTitulo10, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelTitulo11, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(Foto6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 31, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(tlbAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelTitulo12, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Foto1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTitulo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelTitulo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTitulo8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Foto2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Foto3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Foto4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTitulo9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelTitulo10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTitulo11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Foto5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Foto6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)))
                .addGap(39, 39, 39)
                .addComponent(tlbAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTitulo12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jTablePersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Cantidad", "Precio U", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTablePersona.setRowHeight(30);
        jTablePersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePersonajTableUsuarioMouseClicked(evt);
            }
        });
        jScrollPaneTablaPersona.setViewportView(jTablePersona);

        jLabelTitulo1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo1.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabelTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo1.setText("SubTotal:");
        jLabelTitulo1.setFocusCycleRoot(true);
        jLabelTitulo1.setPreferredSize(new java.awt.Dimension(340, 35));

        jLabelTitulo2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo2.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabelTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo2.setText("Orden De Compra");
        jLabelTitulo2.setFocusCycleRoot(true);
        jLabelTitulo2.setPreferredSize(new java.awt.Dimension(340, 35));

        jTextFieldSubTotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldSubTotalFocusLost(evt);
            }
        });
        jTextFieldSubTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldSubTotalMouseClicked(evt);
            }
        });
        jTextFieldSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSubTotalActionPerformed(evt);
            }
        });

        jLabelTitulo3.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo3.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabelTitulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo3.setText("Impuesto:");
        jLabelTitulo3.setFocusCycleRoot(true);
        jLabelTitulo3.setPreferredSize(new java.awt.Dimension(340, 35));

        jTextFieldSubTotal1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldSubTotal1FocusLost(evt);
            }
        });
        jTextFieldSubTotal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldSubTotal1MouseClicked(evt);
            }
        });
        jTextFieldSubTotal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSubTotal1ActionPerformed(evt);
            }
        });

        jLabelTitulo4.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo4.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabelTitulo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo4.setText("Total:");
        jLabelTitulo4.setFocusCycleRoot(true);
        jLabelTitulo4.setPreferredSize(new java.awt.Dimension(340, 35));

        jTextFieldSubTotal2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldSubTotal2FocusLost(evt);
            }
        });
        jTextFieldSubTotal2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldSubTotal2MouseClicked(evt);
            }
        });
        jTextFieldSubTotal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSubTotal2ActionPerformed(evt);
            }
        });

        jButtonIMPRIMIR.setBackground(new java.awt.Color(51, 51, 51));
        jButtonIMPRIMIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/IMPRIMIR.png"))); // NOI18N
        jButtonIMPRIMIR.setToolTipText("Imprimir el reporte");
        jButtonIMPRIMIR.setBorder(null);
        jButtonIMPRIMIR.setBorderPainted(false);
        jButtonIMPRIMIR.setFocusable(false);
        jButtonIMPRIMIR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonIMPRIMIR.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonIMPRIMIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIMPRIMIRActionPerformed(evt);
            }
        });

        jButtonFile.setBackground(new java.awt.Color(51, 51, 51));
        jButtonFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/FOLDER.png"))); // NOI18N
        jButtonFile.setBorder(null);
        jButtonFile.setBorderPainted(false);
        jButtonFile.setFocusable(false);
        jButtonFile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonFile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneTablaPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabelTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabelTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldSubTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabelTitulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldSubTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jButtonIMPRIMIR, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonFile, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(13, 13, 13)))))))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabelTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneTablaPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSubTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitulo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSubTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonIMPRIMIR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonFile, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTablePersonajTableUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePersonajTableUsuarioMouseClicked

    }//GEN-LAST:event_jTablePersonajTableUsuarioMouseClicked

    private void jTextFieldSubTotalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSubTotalFocusLost

    }//GEN-LAST:event_jTextFieldSubTotalFocusLost

    private void jTextFieldSubTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSubTotalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSubTotalMouseClicked

    private void jTextFieldSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSubTotalActionPerformed

    private void jTextFieldSubTotal1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSubTotal1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSubTotal1FocusLost

    private void jTextFieldSubTotal1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSubTotal1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSubTotal1MouseClicked

    private void jTextFieldSubTotal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSubTotal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSubTotal1ActionPerformed

    private void jTextFieldSubTotal2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSubTotal2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSubTotal2FocusLost

    private void jTextFieldSubTotal2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSubTotal2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSubTotal2MouseClicked

    private void jTextFieldSubTotal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSubTotal2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSubTotal2ActionPerformed

    private void jButtonIMPRIMIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIMPRIMIRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonIMPRIMIRActionPerformed

    private void Foto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Foto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Foto1ActionPerformed

    private void Foto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Foto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Foto2ActionPerformed

    private void Foto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Foto3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Foto3ActionPerformed

    private void Foto4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Foto4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Foto4ActionPerformed

    private void Foto5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Foto5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Foto5ActionPerformed

    private void Foto6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Foto6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Foto6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diseño_Punto_De_Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diseño_Punto_De_Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diseño_Punto_De_Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diseño_Punto_De_Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diseño_Punto_De_Venta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Foto1;
    private javax.swing.JButton Foto2;
    private javax.swing.JButton Foto3;
    private javax.swing.JButton Foto4;
    private javax.swing.JButton Foto5;
    private javax.swing.JButton Foto6;
    private javax.swing.JButton jButtonFile;
    private javax.swing.JButton jButtonIMPRIMIR;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JLabel jLabelTitulo10;
    private javax.swing.JLabel jLabelTitulo11;
    private javax.swing.JLabel jLabelTitulo12;
    private javax.swing.JLabel jLabelTitulo2;
    private javax.swing.JLabel jLabelTitulo3;
    private javax.swing.JLabel jLabelTitulo4;
    private javax.swing.JLabel jLabelTitulo5;
    private javax.swing.JLabel jLabelTitulo6;
    private javax.swing.JLabel jLabelTitulo7;
    private javax.swing.JLabel jLabelTitulo8;
    private javax.swing.JLabel jLabelTitulo9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPaneTablaPersona;
    private javax.swing.JTable jTablePersona;
    private javax.swing.JTextField jTextFieldSubTotal;
    private javax.swing.JTextField jTextFieldSubTotal1;
    private javax.swing.JTextField jTextFieldSubTotal2;
    private javax.swing.JButton tlbAdd1;
    // End of variables declaration//GEN-END:variables
}
